pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Upload War To Nexus ') {
            steps {
                nexusArtifactUploader artifacts: [
                    [artifactId: 'my-app', 
                     classifier: '', 
                     file: 'target/my-app-1.0.0.war', type: 'war'
                    ]
                ],
                    credentialsId: 'nexus3',
                    groupId: 'com.mycompany.app',
                    nexusUrl: '172.31.28.91',
                    nexusVersion: 'nexus2', 
                    protocol: 'http', 
                    repository: 'http://18.217.118.60:8081/repository/sampleapp-release/',
                    version: '1.0.0'
            }
    }
}
